name: Python tests
on: [push]

jobs:
  macos_safari:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.5]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        env:
          BROWSER_SELENIUM: 'SAFARI'
        run: tox -e py-django{22}-drf{39}
