name: Python tests
on: [push]

jobs:
  ubuntu-firefox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Prepare Selenium enviroment
        run: |
          #Download geckodriver
          wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
          #Extract geckodriver
          tar -xvzf geckodriver*
          #Make geckodriver execuable
          chmod +x geckodriver
          #Move geckodriver
          sudo mv geckodriver /usr/local/bin/
          #Install Firefox
          sudo apt-get install firefox
          #Set enviroment variable to determine browser
          export BROWSER_SELENIUM='FIREFOX;{"headless": true, "binary_location": "/usr/bin/firefox"}'
          echo '$BROWSER_SELENIUM'
          printenv
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py-django{22}-drf{39}
