name: Python tests
on: [push]

jobs:
  win_edge:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.5]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Da bodo delali fukcionalni testi v Edge-ju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/99
        env:
          BROWSER_SELENIUM: 'EDGE'
        run: tox -e "py-django{22}-drf{39}"
